apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary-rollout
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: canary-study
          image: rogeeoh/ci-study:20
          ports:
            - containerPort: 80
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    canary: #Indicates that the rollout should use the Canary strategy
      maxSurge: "50%"
      maxUnavailable: 0
      steps:
        - setWeight: 10
        - pause:
            duration: 1m # 1 minute
        - setWeight: 20
        - pause:
            duration: 1m # 1 minute
        - setWeight: 30
        - pause:
            duration: 1m # 1 minute
        - setWeight: 40
        - pause:
            duration: 1m # 1 minute
        - setWeight: 50
        - pause:
            duration: 1m # 1 minute
        - pause: {} # pause indefinitely
